class Audio < ActiveRecord::Base
  validates_presence_of :audio_source
  validates_presence_of :word
  validates_presence_of :lang_code
  validates_presence_of :speaker_gender
  # validates_presence_of :forvo_data, :if => audio_source: "forvo" #FIXME
  # validates_presence_of :forvo_id, :if => audio_source: "forvo" #FIXME
  validates_uniqueness_of :forvo_id

  def self.format_forvo_js_for_insert forvo_id
    "<script type=\"text/javascript\" src=\"http://www.forvo.com/_ext/ext-prons.js?id=#{forvo_id.to_s}\" charset=\"utf-8\"></script>".html_safe
  end

  def filename
    "#{self.id.to_s}-#{self.word}"
  end

  def lang_code_hash
    {
    'Abaza' => 'abq',
    'Abkhazian'=> 'ab',
        'Adygean' => 'ady',
        'Afar' => 'aa',
        'Afrikaans' => 'af',
        'Akan' => 'ak',
        'Albanian' => 'sq',
        'Aleut' => 'ale',
        'Amharic' => 'am',
        'Ancient Greek' => 'grc',
        'Arabic ' => 'ar',
        'Aragonese' => 'an',
        'Arbëresh' => 'aae',
        'Armenian' => 'hy',
        'Assamese ' => 'as',
        'Assyrian Neo-Aramaic' => 'aii',
        'Asturian' => 'ast',
        'Avaric' => 'av',
        'Aymara' => 'ay',
        'Azerbaijani' => 'az',
        'Balochi' => 'bal',
        # 'Bambara bm',
        # 'Bardi bcj',
        # 'Bashkir ba',
        # 'Basque  eu',
        # 'Bavarian  bar',
        # 'Belarusian  be',
        # 'Bengali bn',
        # 'Bihari  bh',
        # 'Bislama bi',
        # 'Bosnian bs',
        # 'Botlikh bph',
        # 'Bouyei  pcc',
        # 'Breton  br',
        # 'Bribri  bzd',
        # 'Bulgarian bg',
        # 'Buriat  bxr',
        # 'Burmese my',
        # 'Burushaski  bsk',
        # 'Campidanese sro',
        # 'Cantonese yue',
        # 'Cape Verdean Creole kea',
        # 'Catalan ca',
        # 'Cebuano ceb',
        # 'Central Atlas Tamazight tzm',
        # 'Central Bikol bcl',
        # 'Chamorro  ch',
        # 'Chechen ce',
        # 'Cherokee  chr',
        # 'Chichewa  ny',
        # 'Chuvash cv',
        # 'Cornish kw',
        # 'Corsican  co',
        # 'Cree  cr',
        # 'Creek mus',
        # 'Crimean Tatar crh',
        # 'Croatian  hr',
        # 'Czech cs',
        # 'Dagbani dag',
        # 'Danish  da',
        # 'Dari  prs',
        # 'Dinka din',
        # 'Divehi  dv',
        # 'Dutch nl',
        # 'Dzongkha  dz',
        # 'Emilian egl',
        # 'English en',
        # 'Erzya myv',
        # 'Esperanto eo',
        # 'Estonian  et',
        # 'Eton  eto',
        # 'Ewe ee',
        # 'Ewondo  ewo',
        # 'Faroese fo',
        # 'Fijian  fj',
        # 'Finnish fi',
        # 'Flemish vls',
        # 'Franco-Provençal  frp',
        # 'French  fr',
        # 'Friulan fur',
        # 'Fulah ff',
        # 'Galician  gl',
        # 'Gan Chinese gan',
        # 'Georgian  ka',
        # 'German  de',
        # 'Gilaki  glk',
        # 'Greek el',
        # 'Guarani gn',
        # 'Gujarati  gu',
        # 'Gusii guz',
        # 'Haitian Creole  ht',
        # 'Hakka hak',
        # 'Hassaniyya  mey',
        # 'Hausa ha',
        # 'Hawaiian  haw',
        # 'Hebrew  he',
        # 'Herero  hz',
        # 'Hiligaynon  hil',
        # 'Hindi hi',
        # 'Hiri motu ho',
        # 'Hmong hmn',
        # 'Hungarian hu',
        # 'Icelandic is',
        # 'Igbo  ig',
        # 'Iloko ilo',
        # 'Indonesian  ind',
        # 'Ingush  inh',
        # 'Interlingua ia',
        # 'Inuktitut iu',
        # 'Inupiaq ik',
        # 'Irish ga',
        # 'Italian it',
        # 'Iwaidja ibd',
        # 'Jamaican Patois jam',
        # 'Japanese  ja',
        # 'Javanese  jv',
        # 'Jin Chinese cjy',
        # 'Judeo-Spanish lad',
        # 'Kabardian kbd',
        # 'Kabyle  kab',
        # 'Kalaallisut kl',
        # 'Kalmyk  xal',
        # 'Kannada kn',
        # 'Kanuri  kr',
        # 'Karakalpak  kaa',
        # 'Kashmiri  ks',
        # 'Kashubian csb',
        # 'Kazakh  kk',
        # 'Khanty  kca',
        # 'Khasi kha',
        # 'Khmer km',
        # 'Kikuyu  ki',
        # 'Kimbundu  kmb',
        # 'Kinyarwanda rw',
        # 'Kirundi rn',
        # 'Klingon tlh',
        # 'Komi  kv',
        # 'Kongo kg',
        # 'Konkani gom',
        # 'Korean  ko',
        # 'Kotava  avk',
        # 'Krio  kri',
        # 'Kuanyama  kj',
        # 'Kurdish ku',
        # 'Kutchi  kfr',
        # 'Kyrgyz  ky',
        # 'Lak lbe',
        # 'Lakota  lkt',
        # 'Lao lo',
        # 'Latgalian ltg',
        # 'Latin la',
        # 'Latvian lv',
        # 'Laz lzz',
        # 'Lezgian lez',
        # 'Ligurian  lij',
        # 'Limburgish  li',
        # 'Lingala ln',
        # 'Lithuanian  lt',
        # 'Lombard lmo',
        # 'Louisiana Creole  lou',
        # 'Low German  nds',
        # 'Lozi  loz',
        # 'Luba-katanga  lu',
        # 'Luganda lg',
        # 'Luo luo',
        # 'Lushootseed lut',
        # 'Luxembourgish lb',
        # 'Macedonian  mk',
        # 'Mainfränkisch vmf',
        # 'Malagasy  mg',
        # 'Malay ms',
        # 'Malayalam ml',
        # 'Maltese mt',
        # 'Manchu  mnc',
        # 'Mandarin Chinese  zh',
        # 'Manx  gv',
        # 'Māori mi',
        # 'Mapudungun  arn',
        # 'Marathi mr',
        # 'Mari  chm',
        # 'Marshallese mh',
        # 'Masbateño msb',
        # 'Mauritian creole  mfe',
        # 'Mazandarani mzn',
        # 'Mbe mfo',
        # 'Meitei  mni',
        # 'Mennonite Low German  pdt',
        # 'Mescalero-Chiricahua  apm',
        # 'Micmac  mic',
        # 'Min Dong  cdo',
        # 'Min Nan nan',
        # 'Minangkabau min',
        # 'Mohawk  moh',
        # 'Moksha  mdf',
        # 'Mongolian mn',
        # 'Nahuatl nah',
        # 'Nauru na',
        # 'Navajo  nv',
        # 'Naxi  nxq',
        # 'Ndonga  ng',
        # 'Neapolitan  nap',
        # 'Nepal Bhasa new',
        # 'Nepali  ne',
        # 'Nogai nog',
        # 'North ndebele nd',
        # 'Northern sami sme',
        # 'Norwegian Bokmål  no',
        # 'Norwegian Nynorsk nn',
        # 'Nuosu ii',
        # 'Nǀuu  ngh',
        # 'Occitan oc',
        # 'Ojibwa  oj',
        # 'Okinawan  ryu',
        # 'Oriya or',
        # 'Oromo om',
        # 'Osage osa',
        # 'Ossetian  os',
        # 'Ottoman Turkish ota',
        # 'Palauan pau',
        # 'Palenquero  pln',
        # 'Pali  pi',
        # 'Pangasinan  pag',
        # 'Papiamento  pap',
        # 'Pashto  ps',
        # 'Pennsylvania Dutch  pdc',
        # 'Persian fa',
        # 'Picard  pcd',
        # 'Piedmontese pms',
        # 'Pitjantjatjara  pjt',
        # 'Polish  pl',
        # 'Portuguese  pt',
        # 'Pulaar  fuc',
        # 'Punjabi pa',
        # 'Quechua qu',
        # 'Quiatoni Zapotec  zpf',
        # 'Rapa Nui  rap',
        # 'Rohingya  rhg',
        # 'Romagnol  rgn',
        # 'Romani  rom',
        # 'Romanian  ro',
        # 'Romansh rm',
        # 'Rukiga  cgg',
        # 'Russian ru',
        # 'Rusyn rue',
        # 'Samoan  sm',
        # 'Sango sg',
        # 'Sanskrit  sa',
        # 'Sardinian sc',
        # 'Scots sco',
        # 'Scottish Gaelic gd',
        # 'Seediq  trv',
        # 'Serbian sr',
        # 'Serer srr',
        # 'Shona sn',
        # 'Shoshoni  shh',
        # 'Sicilian  scn',
        # 'Silesian  szl',
        # 'Sindhi  sd',
        # 'Sinhalese si',
        # 'Slovak  sk',
        # 'Slovenian sl',
        # 'Somali  so',
        # 'Sotho st',
        # 'South Ndebele nr',
        # 'Spanish es',
        # 'Sranan Tongo  srn',
        # 'Sundanese su',
        # 'Swabian German  swg',
        # 'Swahili sw',
        # 'Swati ss',
        # 'Swedish sv',
        # 'Swiss German  gsw',
        # 'Sylheti syl',
        # 'Tagalog tl',
        # 'Tahitian  ty',
        # 'Tajik tg',
        # 'Tamil ta',
        # 'Tatar tt',
        # 'Telugu  te',
        # 'Tetum tet',
        # 'Thai  th',
        # 'Tibetan bo',
        # 'Tigrinya  ti',
        # 'Tlingit tli',
        # 'Tok Pisin tpi',
        # 'Toki Pona x-tp',
        # 'Tondano tdn',
        # 'Tonga to',
        # 'Tsonga  ts',
        # 'Tswana  tn',
        # 'Tuareg  tmh',
        # 'Tundra Nenets yrk',
        # 'Turkish tr',
        # 'Turkmen tk',
        # 'Tuscarora tus',
        # 'Tuvan tyv',
        # 'Twi tw',
        # 'Udmurt  udm',
        # 'Ukrainian uk',
        # 'Upper Sorbian hsb',
        # 'Urdu  ur',
        # 'Uyghur  ug',
        # 'Uzbek uz',
        # 'Venda ve',
        # 'Venetian  vec',
        # 'Vietnamese  vi',
        # 'Volapük vo',
        # 'Võro  vro',
        # 'Walloon wa',
        # 'Welsh cy',
        # 'Western Frisian fy',
        # 'Wolof wo',
        # 'Wu chinese  wuu',
        # 'Xhosa xh',
        # 'Xiang Chinese hsn',
        # 'Yakut sah',
        # 'Yeyi  yey',
        # 'Yiddish yi',
        # 'Yoruba  yo',
        # 'Yucatec Maya  yua',
        # 'Yupik esu',
        # 'Zazaki  zza',
        'Zhuang' => 'za',
        'Zulu' => 'zu'
      }
  end

  def self.display!(exercise)
  end


end